apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xcervenkak/mededu-ufe
  newName: xcervenkak/mededu-ufe
  newTag: 1.2.0
- name: xcervenkak/mededu-webapi
  newName: xcervenkak/mededu-webapi
  newTag: 1.2.0

