apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kcrp-mededu-trainings-content
spec:
  microFrontend: kcrp-mededu-ufe
  element: kcrp-mededu-training-list
  attributes:
    - name: api-base
      value: /kcrp-mededu-api
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?kcrp-mededu-trainings(/.*)?$"
