apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xcervenkak/mededu-ufe
  newName: xcervenkak/mededu-ufe # {"$imagepolicy":  "wac-hospital:mededu-ufe:name"}
  newTag: main.20260506.0859 # {"$imagepolicy": "wac-hospital:mededu-ufe:tag"}
- name: xcervenkak/mededu-webapi
  newName: xcervenkak/mededu-webapi # {"$imagepolicy":  "wac-hospital:mededu-webapi:name"}
  newTag: main.20260506.0858 # {"$imagepolicy": "wac-hospital:mededu-webapi:tag"}
